### ISSUE TITLE
SMS is received / notified too seldom

### ISSUE THREAD

**Issue by StaffanMelin** [HelloVolla/volla-os-beta-test#141] opened 2024-01-10 00:04 UTC
See https://forum.volla.online/viewtopic.php?f=36&t=831&p=4248&hilit=sms#p4248.

**Comment by wurzer** [comment] 2024-02-21 17:10
Please recheck it with Volla OS 13. Anyway I can't reproduce it with Volla OS 12.

**Comment by StaffanMelin** [comment] 2024-02-21 20:01
Well, I just experienced both of these issues today. Alarm was 4+ minutes delayed. SMSs notified several minutes they were registered as received.

So either:
1. The notification function is running to seldom
2. There is some power saving function that is "too aggressive".
3. Something else?

**Comment by StaffanMelin** [comment] 2024-02-21 20:01
When is Volla 13 released? I just installed 12.1 (2nd issue).

**Comment by wurzer** [comment] 2024-02-22 10:08
Volla OS 13 will be probably released in March for Volla Phone 22, Volla Phone X23 and Volla Phone X23E. However the public beta is already released for testing.

**Comment by wurzer** [comment] 2024-02-22 10:11
You are using the pre-installed SMS app? You may test swtching off the battery saving mode, because beackground activities are limited or disabled. I don't use the battery save mode anyway.

**Comment by StaffanMelin** [comment] 2024-02-22 22:32
Thanks a lot for this Dr Wurzer, I will try to turn it off. Anyway, I overslept this morning! :D

**Comment by StaffanMelin** [comment] 2024-02-22 22:35
Nah, battery saver was already off, and the built in Messaging/SMS app already had unlimited battery behaviour.

**Closed as completed** 2024-04-14 15:15 UTC
