### ISSUE TITLE
Multiboot wont boot with Ubuntu Touch after latest Volla update

### ISSUE THREAD

**Issue by RinkebyDanceKids** [HelloVolla/volla-os-beta-test#120] opened 2023-11-03 09:53 UTC
Yes, sorry.

I was a happy installer of Ubuntu Touch just a few days ago. Everything worked great, but unfortunally I changed language post  installation. And ubuntu bugged out on me. So I dicided to remove everything and start over. But! You made another push with Volla update to remove Orage State. And now I just cant install Ubuntu anymore. The screen just shine blank, and I have to remove the SD card to make it boot Volla again.

I have tried a lot of order, and different tricks. Reinstalled Ubuntu with new partitions 3-4 times. But now it just wont boot.

My phone is a bit special, and was shipped with orage state for some reason. And the latest, latest update did not remove that, but instead just killed the boot for me.

**Comment by RinkebyDanceKids** [comment] 2023-11-03 18:32
Happy news.

When I saw "Warning kernel still use old partition table". Reboot to update. I rebooted before installing the UT image. And looks like that was the deal! It works again!

**Comment by Danfro** [comment] 2023-11-08 11:30
So rebooting at the right time did fix the error? Then you could maybe close this issue report here, right?

**Closed as completed** 2023-11-08 11:35 UTC

**Comment by RinkebyDanceKids** [comment] 2023-11-08 11:38
I can, but left it open to see if the guys here found it a good solution too. it worked for me.

**Comment by Danfro** [comment] 2023-11-08 11:43
In general I would agree, but since you said, your phone is very special, I guess this is nothing that can be easily reproduced on other phones. Anyway, git keeps it here for reference in case someone needs to look at it again.
